version: '3.8'

services:
  nats-publisher:
    image: ${NEXUS_PRIVATE_REGISTRY_URL}/nats-pub:0.0.1
    build: 
      context: .
      args:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1
    container_name: nats-publisher
    restart: always
    networks:
      - natsops_mspe-network
    command:
      - "-s"
      - "nats://nats-seed:4222" # <NATS server url>:<NATS client port>
      - "data" # NATS subject

networks:
  # Custom user defined bridge network for the NATS server to communicate using domain name
  # Reference to the external network created from the Nexus3 compose file.
  natsops_mspe-network:
    external: true