version: '3.8'

services:
  nats-subscriber-1:
    image: nats-sub:0.0.1
    build: .
    container_name: nats-subscriber-1
    restart: always
    networks:
      - ce_ce-network
    command:
      - "-s"
      - "nats://nats-zone-b:4222" # <NATS server url>:<NATS client port>
      - "data" # NATS subject

  nats-subscriber-2:
    image: nats-sub:0.0.1
    build: .
    container_name: nats-subscriber-2
    restart: always
    networks:
      - ce_ce-network
    command:
      - "-s"
      - "nats://nats-zone-c:4222" # <NATS server url>:<NATS client port>
      - "data" # NATS subject

networks:
  # Custom user defined bridge network for the NATS server to communicate using domain name
  # Reference to the external network created from the Nexus3 compose file.
  ce_ce-network:
    external: true